### PR TITLE
Optimize LoadSse and LoadIntSse

### PR DESCRIPTION
**Pull request by FedyuninV**
Signed-off-by: Valeriy Fedyunin <valery.fedyunin@abbyy.com>

### CODE REVIEW

**Comment by lordnn** [comment]
Only one case was left... looks like assert should be changed on `assert(3 == count)`. Why do you call it an "optimize"?

**Comment by FedyuninV** [comment]
@lordnn I called it `optimize` because it improved the performance of some (kinda exotic, but still used in production) scenario.
The core problem was the `case 0:` in the beginning which is never the case, but is checked on every call (and in some cases this functions are called _a lot_ of times).

The optimization of the condition in the `assert` may be done, but it isn't crucial because the main concern is the performance in non-debug version, when `assert`'s are removed anyway.

**Comment by lordnn** [comment]
`assert` it's not about performance `assert` it's about human understanding about code invariants.

**Comment by FedyuninV** [comment]
@lordnn Then IMO it's more clear that in the beginning of the function it contains the restrictions on `count` (1, 2 or 3).

**Comment by lordnn** [comment]
If `count` enabled to have only one value... it can be removed from the function arguments.

**Comment by lordnn** [comment]
If `count` is 1 or 2 it will be `data` buffer overrun, IMHO.

**Comment by FedyuninV** [comment]
@lordnn Where? If `count` is `1` then returns `return _mm_set_epi32(defVal, defVal, defVal, data[0]);` which makes access only to `data[0]`, same goes for `2` and `3`.

**Comment by lordnn** [comment]
Oops, you're right. 😃

**Pull request merged**
