### PR TITLE
Wrap input names in PyLayer

### PR DESCRIPTION
**Pull request by zimka**
Currently DNN graph structure is inaccessible from NeoML/Python - you can get the list of layers, but you can not read how these layers are connected with each other.
With input names getter it is possible to traverse the whole graph starting from sinks and retrieve it's structure.

It could be used in theory to plot the model, similar to [torchviz](https://github.com/szagoruyko/pytorchviz) or maybe even in a plugin for [netron.](https://github.com/lutzroeder/netron/blob/main/source/pytorch.py)

Also fixes incorrect `assertTrue` which are supposed to be `assertEqual`

### CODE REVIEW

**Comment by FedyuninV** [comment]
The idea is really good, but I think it's better to provide list of tuples `(input_layer_name, output_index)`. Current solution doesn't provide enough info if model has layers with multiple outputs (e.g. SplitSomeDimension).

**Comment by zimka** [comment]
I agree that `input_output_index` is necessary to retreive precise graph structure, but in my opinion the list of tuples `(input_layer_name, output_index)` is not the best way to handle the problem.
1. Output index of input is needed only in some specific cases, while in most cases there is either no order at all (single output) or the order does not matter (eltwise sum/prod)
2. "Output Index of Input with Index" is quite clumsy concept, which is not obvious from the first glance. It could be better to wrap CDnnLayerLink, which has more intuitive meaning, but this is out of this PR scope 

I have added one more method `get_input_output_index` and tests for it, please check if you are fine with it

**Comment by FedyuninV** [comment]
1. Agree. My idea now is to add both `input_names` and `inputs`.
2. Agree, but I think we can avoid such awkward names like `get_input_output_idx`.

Here is the idea:
```
@property
def inputs(self):
   ''' Tuple in which i'th element contains information about the layer connected to the i'th input of `self` (name, output number)
   '''
   return tuple( ... )

@property
def input_names(self):
   ''' Tuple in which i'th element contains the name of the layer, connected to the  i'th inputs of `self`
   '''
   return tuple( layer_name for layer_name, _ in self.inputs )
```

The things I don't like in current implementation are _Why we have input_names as property, but we have to call method with possibility of wrong idx being passed for getting info about output index? Why these methods are so different?_

**Comment by zimka** [comment]
Yep, these questions sound reasonable. 
I have replaced `.get_input_output_idx` in PyLayer interface with `input_links` property, it returns tuple of tuples. I have kept the internal method, because it actually mimics CBaseLayer interface.

I think `.inputs` would be unclear, because it could be layer instances for example, IMO `input_links` describes it more precisely.
Hope one day there will be pybinded `CDnnLayerLink`s instead of tuples

**Review by FedyuninV — APPROVED** [review]

**Pull request merged**
